# jekyll-theme-h2o-ac
version: 1.5.1

# Site settings é…ç½®ç«™ç‚¹
title: 'Yucol'
description: 'ä¸ªäººçš„ä¸€ä¸ªæŠ€æœ¯åšå®¢ç«™ç‚¹ï¼Œä¸»è¦ç”¨äºè®°å½•ä¸ªäººåœ¨å­¦ä¹ è¿‡ç¨‹ä¸­é‡åˆ°çš„æŠ€æœ¯é—®é¢˜åŠè§£å†³æ–¹æ³•ã€ä»¥åŠä¸€äº›æ¯”è¾ƒæœ‰è¶£çš„äº‹æƒ…ã€‚'
keyword: 'yucolï¼Œyucolçš„åšå®¢ï¼Œbaoziï¼Œpythonï¼Œå‰ç«¯ï¼Œåæ®µï¼Œæ™ºæ…§å†œä¸š'
url: 'https://jmbaozi.github.io' # your host

# when build blog on server, if you don't need baseurl, you should leave this value blank.
# åœ¨æœåŠ¡å™¨ä¸Šå»ºç«™æ—¶ï¼Œå¦‚æœä½ ä¸éœ€è¦å­åŸŸåï¼Œè¯·å°†è¿™ä¸€æ ¼ç•™ç©º
# if you're using GitHub Pages, set baseurl to your blog's .
# å¦‚æœä½ åœ¨ä½¿ç”¨ GitHub Pages, è¯·å°† baseurl è®¾ç½®ä¸ºä½ çš„ç½‘å€çš„å­åŸŸå
# for example, if your site is "kaeyleo.github.io", then this url should leave blank.
# ä¾‹å¦‚ï¼Œå½“ä½ çš„åŸŸåæ˜¯ "kaeyleo.github.io"  æ—¶ï¼Œè¿™ä¸ª url éœ€è¦ç•™ç©º
# but if your created a repo named "myblog", and the site is "kaeyleo.github.io/myblog", change baseurl to '/myblog'
# ä½†æ˜¯ï¼Œå¦‚æœä½ åˆ›å»ºäº†ä¸€ä¸ªå« "myblog" çš„ç½‘ç«™ï¼Œæ­¤æ—¶ç½‘å€ä¼šå˜æˆ "kaeyleo.github.io/myblog" ï¼Œè¿™æ—¶å†å°† baseurl è®¾ç½®ä¸º '/myblog'
baseurl: ''

# Internalization å›½é™…åŒ–
languages: ["zh-Hans", "zh-Hant", "en", "ja"]
default_lang: "zh-Hans"

# Github
github:
  enabled: true
  owner: yucol
  repository: jekyll-theme-H2O-ac

# PWA
pwa:
  color: '#81BBFF'
  short_name: 'lisz'

# Navigation links
nav:
  home: '/'
  blog: '/blog/index.html'
  archives: '/archives.html'
  tags: '/tags.html'
  about:   
    RSS: '/feed.xml'
    HALL: '/hall/'

# Gray for the whole site å…¨ç«™ç°è‰²
gray: false

# Formats
# æ—¶é—´æ ¼å¼ï¼ˆTime formatï¼‰ï¼š0 -- 2022-04-29    1 -- 29 Apr 2022   2 -- 2022å¹´4æœˆ29æ—¥
formats:
  time: 0   

# Favicon
favicon: "/favicon.ico"

# Footer
footer:
  since: 2020

# Author é…ç½®åšä¸»ä¿¡æ¯
author: 'yucol'
nickname: 'yucol'
bio: 'ğŸŒŠ ç™½å¤©æƒ³ï¼Œå¤œé‡Œå“­ï¼Œåšæ¢¦éƒ½æƒ³å»çœ‹æµ·'
avatar: '/assets/img/profile_photo.jpg'

# Search
search: true

# Night mode
nightMode: false

# Comments è¯„è®ºåŠŸèƒ½
comments:
  disqus: true
  disqus_url: 'https://yucol.disqus.com/embed.js'
  waline: true
  waline_url: 'https://waline-hello-world-mocha.vercel.app/'
  waline_reaction: true
  waline_locale: "{reaction0: 'èµä¸€ä¸ª', reaction1: 'è¸©ä¸€ä¸‹', reaction2: 'æœ‰ç‚¹é…·', reaction3: 'çœ‹ä¸æ‡‚', reaction4: 'å•¥ç©æ„', reaction5: 'æƒ³ç¡è§‰'}"
  artalk: false
  artalk_url: 'https://artalk.lisz.top'
  artalk_name: 'h2o-ac'
  artalk_uaBadge: false
  utterances: false
  utterances_url: 'https://utteranc.es/client.js'
  # utterances_repo: 'zhonger/utterances-comments'
  giscus: false
  giscus_url: 'https://giscus.app/client.js'
  # giscus_repo: 'zhonger/giscus-comments'
  # giscus_repo_id: 'R_kgDONLt80A'
  # giscus_category_id: 'DIC_kwDONLt80M4CkDnG'
  giscus_lang: 'zh-CN'
  twikoo: false
  twikoo_url: 'https://twikoo.lisz.top'
  # twikoo_region: 'ap-shanghai'
  # twikoo_lang: 'zh-CN'

# MathJax å…¬å¼æ”¯æŒ by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color ä¸»é¢˜çš®è‚¤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings é…ç½®ç¤¾äº¤ç½‘ç«™
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  # google-scholar: 'https://scholar.google.com/citations?user=AUupIooAAAAJ'
  # researchgate: 'https://www.researchgate.net/profile/Shengzhou-Li'
  # ORCID: 'https://orcid.org/0000-0001-6973-3825'
  github: 'https://github.com/JMbaozi'
  weibo: 'https://weibo.com/3958305706'
  twitter: 'https://x.com/Yucoly'
  instagram: 'https://www.instagram.com/yucoled/'
  # linkedin: 'https://www.linkedin.com/in/shengzhouli/'
  # segmentfault: 'https://segmentfault.com/u/wuwozhonger'

# Links å‹æƒ…é“¾æ¥
links:
  'åŒ—å±¿': 'https://blog.bj-yan.top/'
  'PYQ': 'https://peng-yq.github.io/'
  'VnYzm': 'https://zimingyuan.github.io/'
  'ZhangZhao Blog': 'https://zhangzhao219.github.io/'
  'é›…ä½™': 'https://yayu.net/'
  'æ±Ÿå¿«è·‘': 'https://jiangkp.com/'
  'Mr Li': 'https://lisz.me'



# Calendar æ—¥å†
calendar: true

# Supports èµåŠ©å•†
supports:
  upyun: 
  webify: 

# Badges
badges:
  netlify: true # Netlify
  vercel: true # Vercel
  cloudflare: true # Cloudflare
  foreverblog: true # Foreverblog
  wormhole: true # Wormhole
  travelling: true # Travelling
  notbyAI: true # NotByAI

# Alive time
alivetime: true
alivestart: "02/10/2020"

# Beian å¤‡æ¡ˆå·
# beian: 'æ²ªICPå¤‡xxxxxxxxå·'
moe_beian: '20200502'

# CC License
cclicense: true

# CNZZ Analytics
# cnzz: 1234567891
cnzz: 

# Busuanzi Analytics
busuanzi: true
busuanzi_url: 'https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'

# Umami Analytics
umami:
  status: 
  id: 
  js: 

# Shynet Analytics
shynet: false
shynet_url: ''

# Plausible Analytics
plausible: false
plausible_domain: 'example.com'
plausible_url: ''
# plausible_js: ''

# Fathom Analytics
fathom: false
fathom_id: ''

# Ackee Analytics
ackee: false
ackee_url: ''
ackee_id: ''
# ackee_js: ''

# Matomo Analytics
matomo: false
matomo_url: ''
matomo_id: ''

# Google Analytics
# google_analytics: UA-XXXXXXXXX-X
google_analytics: 

# Google Search
google_search: 

# ToS
tos: /tos.html

# Tags è®¾ç½®æ ‡ç­¾
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
pagination:
  enabled: true
  per_page: 10
  permalink: 'page:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

exclude: ['node_modules', 'dev', 'package.json', 'webpack.config.js', '.gitignore', 'README.md', '*.gemspec', '*.gem']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Prism settings
# Support all offical and extended themes
# Please visit https://prismjs.com and https://github.com/PrismJS/prism-themes/tree/master/themes to check the supported theme names
prism:
  theme: one-light
  line_numbers: true

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:categories/:title.html

# Extlinks
extlinks:
  attributes: {rel: nofollow, target: _blank, class: extlinks}
  # rel_exclude: ['host1.com', 'host2.net']
  # class_exclude: ['host1.com', 'host2.net']

# Mermaid
mermaid: true

# TOC
toc: true
# <div class="title">{% if title %} {{title}} {% else %} {{default_title}} {% endif %}</div>
# premonition
premonition:
  default:
    template: '<div class="premonition {{type}}">
          <div class="header">
            <svg class="icon {{type}}" aria-hidden="true">
                <use xlink:href="#icon-{{type}}"></use>
            </svg>
            <div class="title"> {{title}} </div>
          </div>
          <div class="content">
            {{content}}
          </div>
        </div>'
  types:
    citation:
      template: '<div class="premonition {{type}}">
          <div class="header">
            <svg class="icon {{type}}" aria-hidden="true">
                <use xlink:href="#icon-{{type}}"></use>
            </svg>     
          </div>
          <div class="content">
            {{content}}
          </div>
          {% if title %}<div class="ref"> ------ {{title}} </div>{% endif %}
        </div>'
      default_title: ''
    note:
      default_title: 'Note'
    info:
      default_title: 'Info'
    warning:
      default_title: 'Warning'
    error:
      default_title: 'Error'

# Plugins
plugins: [jekyll-paginate-v2, jekyll-feed, jekyll-sitemap, premonition, h2o-ac-jekyll-extlinks]